apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-exporter-monitor
  namespace: custom-exporter
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 5m
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 5m
      tlsConfig:
        insecureSkipVerify: true
  jobLabel: app
  namespaceSelector:
    matchNames:
      - custom-exporter
  selector:
    matchLabels:
      app: sample-exporter